version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-node-network

  app:
    build: ./Dockerfile
    container_name: node-app
    ports:
      - 3000:3000
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
    networks:
      - mongo-node-network

networks:
  mongo-node-network:
    driver: bridge

volumes:
  mongo-data:
